In [2]:
import pandas as pd
df = pd.read_csv("admissions_messy - admissions_messy.csv")
print(df)

      Application ID  Applicant Name                  Email Intended Major  \
0             1352.0       wanda DOE         wdoe@gmail.com           Math
1             1689.0     PETER JONES         pjones@edu.org     Journalism
2             1485.0  wanda MAXIMOFF    wmaximoff@yahoo.com           Math
3             1388.0    PETER Parker      pparker@yahoo.com    Agriculture
4             1031.0    bruce rogers      brogers@stark.com        Physics
...              ...             ...                    ...            ...
1045          1330.0  diana MAXIMOFF      dmaximoff@edu.org            NaN
1046          1466.0     STEVE Allen         sallen@edu.org     Journalism
1047          1121.0  Charlie ROGERS      crogers@stark.com        History
1048          1299.0     peter Wayne  pwayne@dailybugle.com     Journalism
1049             NaN   CHARLIE Brown       cbrown@yahoo.com       Business

     High School State Application Fee Submission Date
0                   NV         $297.91         pending
1                  NaN       $1,939.68      08/14/2023
2                  NaN         $277.90      2023/06/06
3                   AZ         $370.25      2023-02-24
4                   NV          $53.93    Oct 16, 2023
...                ...             ...             ...
1045                AZ         $862.30      10-18-2023
1046               NaN         $389.22      10-20-2023
1047                AZ       $1,746.27    Aug 17, 2023
1048                KS         $689.05      2023-06-06
1049                KS      $1,875.22          unknown

[1050 rows x 7 columns]

Handling Missing Data: The dataset is riddled with NaNs. You must use .dropna() to remove rows completely missing an Application ID. You will use .fillna() to replace missing Intended Major and High School State values with "Unknown" that were lost during the export.

In [3]:
df1 = df.dropna(subset=['Application ID'])
df1

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,$689.05,2023-06-06

In [4]:
df2 = df1.copy()
fill_Intended_Major_and_hight_school = df2[['Intended Major','High School State']].fillna('Unknown')
fill_Intended_Major_and_hight_school

        Intended Major High School State
0                 Math                NV
1           Journalism           Unknown
2                 Math           Unknown
3          Agriculture                AZ
4              Physics                NV
...                ...               ...
1044  Computer Science                KS
1045           Unknown                AZ
1046        Journalism           Unknown
1047           History                AZ
1048        Journalism                KS

[943 rows x 2 columns]

Handling Duplicates: A server glitch caused applicants to accidentally submit identical applications twice. You must use .duplicated() to find identical application rows and .drop_duplicates(keep='first') to remove the errors and keep only the original submission.

In [5]:
df3 = df2.copy()
is_duplicated = df2.duplicated()
is_duplicated

0       False
1       False
2       False
3       False
4       False
        ...
1044    False
1045    False
1046    False
1047    False
1048     True
Length: 943, dtype: bool

In [6]:
df4 = df3.copy()
df_drop_first = df2.drop_duplicates(keep='first')
df_drop_first

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1043,1871.0,Arthur Wayne,awayne@gmail.com,Art,NJ,"$1,619.10",05-07-2023
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"

Application Fee is imported as a string (e.g., "$150.50"). You must remove the symbols and use pd.to_numeric() to turn it into a float.

In [7]:
df5 = df4.copy()
df5['Application Fee'] = df5['Application Fee'].astype(str).str.replace(r'[^\d.]', '', regex=True)
df5['Application Fee'] = pd.to_numeric(df5['Application Fee'], errors='coerce')
df5['Application Fee']

0        297.91
1       1939.68
2        277.90
3        370.25
4         53.93
         ...
1044    1582.76
1045     862.30
1046     389.22
1047    1746.27
1048     689.05
Name: Application Fee, Length: 943, dtype: float64

Replace “pending” and “unknown” text entries in the dates with the previous valid datetime (forward filling).

In [9]:
df6 = df5.copy()
df6['Submission Date'] = pd.to_datetime(df6['Submission Date'], errors='coerce')
df6['Submission Date'] = df6['Submission Date'].ffill()
df6

C:\Users\USER\AppData\Local\Temp\ipykernel_14884\2952719222.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df6['Submission Date'] = pd.to_datetime(df6['Submission Date'], errors='coerce')

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,297.91,NaT
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,1939.68,2023-08-14
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,277.90,2023-06-06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,53.93,2023-10-16
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,1582.76,2023-05-27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,862.30,2023-10-18
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,389.22,2023-10-20
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,1746.27,2023-08-17
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,689.05,2023-06-06

Convert Submission Date from messy text into a proper datetime object using pd.to_datetime().

In [10]:
df7 = df6.copy()
df7['Submission Date'] = pd.to_datetime(df7['Submission Date'], errors='coerce', 
    format='mixed'
)
df7

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,297.91,NaT
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,1939.68,2023-08-14
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,277.90,2023-06-06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,53.93,2023-10-16
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,1582.76,2023-05-27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,862.30,2023-10-18
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,389.22,2023-10-20
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,1746.27,2023-08-17
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,689.05,2023-06-06

Convert the Submission Date format from various mixed formats into a uniform "M/D/Y" format.

In [11]:
df8 = df7.copy()
df8['Submission Date'] = pd.to_datetime(df8['Submission Date'], errors='coerce')
df8['Submission Date'] = df8['Submission Date'].dt.strftime('%m/%d/%Y')
df8

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,297.91,NaN
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,1939.68,08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,277.90,06/06/2023
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,370.25,02/24/2023
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,53.93,10/16/2023
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,1582.76,05/27/2023
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,862.30,10/18/2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,389.22,10/20/2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,1746.27,08/17/2023
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,689.05,06/06/2023

String Manipulation: The Applicant Name column has chaotic capitalization and extra spaces. You will use .str.title() and .str.strip() to fix this. You must also extract the email domain (e.g., extracting "yahoo.com" from "student@yahoo.com") using .str.split() to see which email providers are most common.

In [12]:
df9 = df8.copy()
df9['Applicant Name'] = df9['Applicant Name'].str.strip().str.title()
df9

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,Wanda Doe,wdoe@gmail.com,Math,NV,297.91,NaN
1,1689.0,Peter Jones,pjones@edu.org,Journalism,NaN,1939.68,08/14/2023
2,1485.0,Wanda Maximoff,wmaximoff@yahoo.com,Math,NaN,277.90,06/06/2023
3,1388.0,Peter Parker,pparker@yahoo.com,Agriculture,AZ,370.25,02/24/2023
4,1031.0,Bruce Rogers,brogers@stark.com,Physics,NV,53.93,10/16/2023
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,1582.76,05/27/2023
1045,1330.0,Diana Maximoff,dmaximoff@edu.org,NaN,AZ,862.30,10/18/2023
1046,1466.0,Steve Allen,sallen@edu.org,Journalism,NaN,389.22,10/20/2023
1047,1121.0,Charlie Rogers,crogers@stark.com,History,AZ,1746.27,08/17/2023
1048,1299.0,Peter Wayne,pwayne@dailybugle.com,Journalism,KS,689.05,06/06/2023

In [12]:
df10 = df9.copy()
df10['domain'] = df10['email'].str.split('@').str[1]
df10
df['domain'] = df['Email'].str.split('@').str[1]
print(df)

      Application ID  Applicant Name                  Email Intended Major  \
0             1352.0       Wanda Doe         wdoe@gmail.com           Math
1             1689.0     Peter Jones         pjones@edu.org     Journalism
2             1485.0  Wanda Maximoff    wmaximoff@yahoo.com           Math
3             1388.0    Peter Parker      pparker@yahoo.com    Agriculture
4             1031.0    Bruce Rogers      brogers@stark.com        Physics
...              ...             ...                    ...            ...
1045          1330.0  Diana Maximoff      dmaximoff@edu.org            NaN
1046          1466.0     Steve Allen         sallen@edu.org     Journalism
1047          1121.0  Charlie Rogers      crogers@stark.com        History
1048          1299.0     Peter Wayne  pwayne@dailybugle.com     Journalism
1049             NaN   Charlie Brown       cbrown@yahoo.com       Business

     High School State  Application Fee Submission Date          domain
0                   NV           297.91             NaN       gmail.com
1                  NaN          1939.68      08/14/2023         edu.org
2                  NaN           277.90      06/06/2023       yahoo.com
3                   AZ           370.25      02/24/2023       yahoo.com
4                   NV            53.93      10/16/2023       stark.com
...                ...              ...             ...             ...
1045                AZ           862.30      10/18/2023         edu.org
1046               NaN           389.22      10/20/2023         edu.org
1047                AZ          1746.27      08/17/2023       stark.com
1048                KS           689.05      06/06/2023  dailybugle.com
1049                KS          1875.22      06/06/2023       yahoo.com

[1050 rows x 8 columns]